workflows:
  react-native-android:
    name: React Native Android Build
    instance_type: default
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.cartasParaMiAmorcito.app"
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build web
        script: npm run build
      - name: Setup Android
        script: |
          npx cap add android || true
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew clean assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
