workflows:
  react-native-android:
    name: React Native Android Build
    instance_type: mac_mini
    max_build_duration: 120
    environment:
      java_version: temurin-11
      ndk_version: r21e
      node: 16
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build web
        script: npm run build
      - name: Setup Android
        script: |
          npx cap add android || true
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew clean assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
