workflows:
  react-native-android:
    name: React Native Android Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.cartasParaMiAmorcito.app"
    triggering:
      events:
        - push
    scripts:
      - name: Install and build
        script: |
          cd cartas
          npm install
          npm run build
      - name: Setup Android and icons
        script: |
          cd cartas
          npx cap add android || true
          npx cap sync android
          # Copy PNG icon to all mipmap folders using bash
          for dir in mipmap-hdpi mipmap-mdpi mipmap-xhdpi mipmap-xxhdpi mipmap-xxxhdpi; do
            if [ -d "android/app/src/main/res/$dir" ]; then
              cp -f ic_launcher.png "android/app/src/main/res/$dir/ic_launcher.png" 2>/dev/null || echo "Icon copied to $dir"
            fi
          done
      - name: Build APK
        script: |
          cd cartas/android
          chmod +x ./gradlew
          ./gradlew clean assembleDebug
    artifacts:
      - cartas/android/app/build/outputs/apk/debug/app-debug.apk
